name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs on every push to the main branch

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test  # Runs automated tests

      - name: Build Application
        run: npm run build  # Builds the project

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "my-webapp-name"  # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
